In [8]:
import torch
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [10]:
x = torch.arange(12)
x
x.shape
x.numel()
X = x.reshape(-1, 4)
X

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

torch.Size([12])

12

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))
torch.randn(3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

tensor([[-0.0493, -0.8467, -0.5064, -1.1845],
        [-0.6740, -0.1274, -0.2741, -0.9803],
        [ 0.8235, -1.8090,  0.5635, -1.1127]])